name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache data
        id: cache-data
        uses: actions/cache@v3
        with:
          path: prepared-data
          key: prepared-data-${{ hashFiles('prepare-data.sh') }}
      - name: Download data
        if: steps.cache-data.outputs.cache-hit != 'true'
        run: |
          bash prepare-data.sh
      - name: Run the pipeline
        run: |
          docker run \
            -w /workdir \
            -v ${{ github.workspace }}/:/workdir \
            -v /tmp \
            -v ${{ github.workspace }}/prepared-data:/mnt \
            justold/immunopipe:dev \
            --config config.toml
      - name: Deploy to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: output
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
